version: '3'
services:
  postgres:
    image: 'postgres:11.1-alpine'
    container_name: user-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user_db
    volumes:
      #      - ./init-greeting-db.sql:/docker-entrypoint-initdb.d/init-greeting-db.sql
      - ./user-db-data:/var/lib/postgresql/data
